### ISSUE TITLE
Update CVSS from 3.1 to 4

### ISSUE THREAD

**Issue by ryukk33** [certmichelin/PTART#112]
Hello, do you plan to update cvss 3.1 to cvss 4? 

thanks by advance and have a nice day !

source: https://www.first.org/cvss/v4-0/

**Comment by Fisjkars** [comment]
Hello, yes an update will be developed for that feature, however it's not so simple because the old notation need to be kept for existing projects.
No release date is scheduled right now.

++++

**Comment by Fisjkars** [comment]
CVSSv4 has been added in PTART today, enjoy !!!
