### ISSUE TITLE
setup - OTP

### ISSUE THREAD

**Issue by noraj** [certmichelin/PTART#72]
On first login the OTP secret is shown as a QR code.

![image](https://user-images.githubusercontent.com/16578570/163731172-374270b1-cbbe-4a7b-bef4-24aea19b8d31.png)

There should also be the secret key shown as text for people who don't necessary have a smartphone or a working camera.

**Comment by Fisjkars** [comment]
![image](https://user-images.githubusercontent.com/1435052/164409709-5643438c-f88f-479c-b0cd-a0c2429bcce4.png)

Done, the key is now displayed
