### ISSUE TITLE
OWASP Top 10 labels

### ISSUE THREAD

**Issue by noraj** [certmichelin/PTART#73]
update https://github.com/certmichelin/PTART/blob/master/data/owasp_top10_label.json from OWASP top 10 2017 to OWASP top 10 2021

cf. https://owasp.org/www-project-top-ten/

PS: OWASP top 10 is not a category system but the 10 most common vulns in a privater group of enterprizes

**Comment by Fisjkars** [comment]
I added the last top 10 from OWAPS, some more devs has been required (add deprecated field to labels), in order to have too much labels during the hit management.
