### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by noraj** [certmichelin/PTART#74]
For example on the administration pages, the pagination is weirdly displayed. The page numbers are joined (no splitter) which make it hard to read.

![image](https://user-images.githubusercontent.com/16578570/163731602-898f215b-2fc5-443a-8d46-91619ae68c7a.png)

**Comment by Fisjkars** [comment]
![image](https://user-images.githubusercontent.com/1435052/166234985-a8951394-592b-40fa-ad7f-87a8fb05f216.png)

I changed the table template to django_tables2/bootstrap4.html that improve the pagination
