### ISSUE TITLE
behavior after a project creation

### ISSUE THREAD

**Issue by noraj** [certmichelin/PTART#75]
When a new project was added (http://127.0.0.1:8000/projects/new/) instead of just displaying a success alert and reset the form, it should redirect to the project list page (http://127.0.0.1:8000/projects/) or to the newly created template (http://127.0.0.1:8000/project/1/summary).

![image](https://user-images.githubusercontent.com/16578570/163731704-19fa8209-4e2b-409e-a77b-300759f197c2.png)

**Comment by noraj** [comment]
Same for assessments

**Comment by Fisjkars** [comment]
It was implement for projects, however assessment is often created in bulk, so we keep the current behavior for them.
