### ISSUE TITLE
CVSS v3.1

### ISSUE THREAD

**Issue by noraj** [certmichelin/PTART#76]
update CVSS from 3.0 to 3.1

![image](https://user-images.githubusercontent.com/16578570/163731811-91f97b00-ed97-43e2-9a7c-1b0a5f3cb2e5.png)

cf. https://www.first.org/cvss/v3-1/

**Comment by Fisjkars** [comment]
Hello, thanks for idea, the change has been implemented : https://github.com/certmichelin/PTART/commit/3d4412a12cec3fd572475156b8350956bd160eac
