### ISSUE TITLE
Report system

### ISSUE THREAD

**Issue by noraj** [certmichelin/PTART#79]
There is a light system called "HTML report" in PTART but it is not a report but rather some slides.
There is no way to create a custom template to output a PDF or docx/odt.

I was expecting something similar to Pwndoc https://pwndoc.github.io/pwndoc/#/docxtemplate or PCF https://gitlab.com/invuls/pentest-projects/pcf/-/wikis/Reports%20moderation or many others listed [here](https://inventory.raw.pm/tools.html#title-tools-collaboration-report).

**Comment by Fisjkars** [comment]
Latex report is part of our roadmap, however this feature requires some heavy development and analysis it should be done for Q3 2022

**Comment by noraj** [comment]
A lighter alternative would be to have markdown as input and to use https://docxtpl.readthedocs.io/en/latest/ or https://openpyxl.readthedocs.io/en/stable/ to output a docx

**Comment by Fisjkars** [comment]
Hello @noraj, normally a full LaTeX report has been released yesterday ;) so I close this issue
